name: Java CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   
          
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: saksham0197/app:latest    

           
      - name: Build artifacts
        uses: actions/upload-artifact@v2
        with:
         name: github_Actions_ Artifacts
         path: src

      - name: Sonar Cloud Scanning
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=saksham0197_Maven001
            
      - name: Test with Maven
        run: mvn -B test --file pom.xml
        
      - name: Retrieve SonarCloud data
        run: |
          # Make HTTP requests to SonarCloud API
          curl -X GET https://sonarcloud.io/api/project_badges/measure?project=saksham0197_Maven001&metric=code_smells,vulnerabilities,ncloc,duplicated_lines_density
